apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: FinRisk-API
    type: simpod-json-datasource
    url: http://api:8000
    access: proxy
    isDefault: false
